### ISSUE TITLE
Create cards/materials for kickoff meeting

### ISSUE THREAD

**Issue by davemcorwin** [18F/doj-it-pa#15]

**Comment by Jacklynn** [comment]
@AvivaOskow Aviva has already made the cards to of the services. Aviva, when formatted can you print them out? Plus a bunch of blank ones?

**Comment by AvivaOskow** [comment]
@Jacklynn were you able to print anything off yesterday? If not, I won't have access to a printer until I arrive in DC later today, but I can head straight to the office to get materials ready.

**Comment by Jacklynn** [comment]
I wasn't, but I'm planning on heading to the office anyway to collect the
workshop materials. I just didn't know if you had the cards made or not.

**Comment by Jacklynn** [comment]
Source file for creating the physical cards

[Cards.zip](https://github.com/18F/doj-it-pa/files/2384809/Cards.zip)
