### ISSUE TITLE
Digitize kick-off materials

### ISSUE THREAD

**Issue by Jacklynn** [18F/doj-it-pa#18]
We created a lot of material from the kick-off that we want to digitize so the whole team (and stakeholders) have access to it. 

The content types I we have right now are...

- [x] OCIO services
- [x] Component provided services
- [x] Fears & Hopes
- [x] Opportunity areas
- [x] Parking lot & meeting notes board
- [x] Slide deck for presentation.

**Comment by Jacklynn** [comment]
Just need the OCIO Services update

**Comment by AvivaOskow** [comment]
Will do this today! @Jacklynn

**Comment by timothy-spencer** [comment]
Can we add the deck we used to this list?  I know that at least one of the folks asked us if that would be available to them.

**Comment by Jacklynn** [comment]
Done! I added it as part of the deliverables we could give to Allyson tomorrow in [this folder](https://drive.google.com/drive/u/0/folders/1arTONA_RIuWesAT9UDPFQlYABJO1BCQg). 

Marking this issue as done because Aviva also finished the ocio services bit.

**Comment by AvivaOskow** [comment]
Is this good to close now?

**Comment by Jacklynn** [comment]
It is closed :)
