### ISSUE TITLE
[wk 3] Highlight/Synthesize research

### ISSUE THREAD

**Issue by Jacklynn** [18F/doj-it-pa#22]
Synth research from last week. Owner: Tim

Suggestion: to start considering criteria of what might make a good candidate (Ex: what’s makes a good opportunity? types of sharing)

- [x] Tim's Kick off notes (Tim)
- [x] Oleysa's kick off notes (jacklynn)
- [x] Afternoon session CRT
- [x] Afternoon session ENRD
- [x] Afternoon session TAX
- [x] ENRD handout (Tim)

**Comment by timothy-spencer** [comment]
@Jacklynn is now doing the ENRD handout!  Thanks Jacklynn!

**Comment by Jacklynn** [comment]
Finished reading and left notes in the [Reading Index](https://docs.google.com/document/d/1bAAxtJGTwRjhVuZ_cXhoLpquiGzyc-25FvE8TBbcmpk/edit#)
