### ISSUE TITLE
Have initial interview with ENRD Leadership

### ISSUE THREAD

**Issue by timothy-spencer** [18F/doj-it-pa#36]
In order to gather data that we need to make good recommendations, we need to:
- [x] Schedule the meeting
- [x] Create the agenda
- [x] Create the interview plan and related exercises
- [x] Conduct the meeting and gather the data
- [x] Send a followup email
- [ ] Do something with the data:  synthesize/document/present/integrate/???

**Comment by Jacklynn** [comment]
@AvivaOskow @timothy-spencer I compared the excel sheet Rick emailed back to us and updated [our spreadsheet](https://docs.google.com/spreadsheets/d/1KdGnkRJHW9PhYO7B17xPVuIKFZ79ZQPACQZir7-ArbQ/edit#gid=1614376693) with the additional component level services he added. They're indicated with a *blue x*.

there didn't appear to be any changes to JMD services

**Comment by timothy-spencer** [comment]
@nikzei scheduled the meeting

The interview plan is here:  https://docs.google.com/document/d/1d3mmY43Ib72NBhOfb7ZW0Xf7DKVaJu0syqfMJIR4qIM/edit#  It's not done, but it's mostly there.
