### ISSUE TITLE
Have initial interview with CRT leadership

### ISSUE THREAD

**Issue by timothy-spencer** [18F/doj-it-pa#37]
In order to gather data that we need to make good recommendations, we need to:
- [x] Schedule the meeting
- [x] Create the agenda
- [x] Create the interview plan and related exercises
- [x] Conduct the meeting and gather the data
- [ ] Send a followup email
- [ ] Do something with the data:  synthesize/document/present/integrate/???

**Comment by Jacklynn** [comment]
Conversation guide I created is in the Research folder, linked [here](https://docs.google.com/document/d/1yk7CBi8k0rtflG3nYdxXnducqHWRR2OiPkZMyNIrdxg/edit).

Will + folks in to review once it's scheduled.

**Comment by Jacklynn** [comment]
Whoops, ignore previous comment, was meant for the JMD Service level issue!
