### ISSUE TITLE
Have initial meeting with JMD Service Level

### ISSUE THREAD

**Issue by timothy-spencer** [18F/doj-it-pa#38]
In order to gather data that we need to make good recommendations, we need to:
- [x] Schedule the meeting
- [x] Create the agenda
- [x] Create the interview plan and related exercises
- [x] Conduct the meeting and gather the data
- [x] Send a followup email
- [x] Do something with the data:  synthesize/document/present/integrate/???

**Comment by Jacklynn** [comment]
Conversation guide I created is in the Research folder, linked [here](https://docs.google.com/document/d/1yk7CBi8k0rtflG3nYdxXnducqHWRR2OiPkZMyNIrdxg/edit).

Will + folks in to review once it's scheduled.
