### ISSUE TITLE
[Sprint 9/7] Follow up with Allyson re: capabilities of kick-off room

### ISSUE THREAD

**Issue by Jacklynn** [18F/doj-it-pa#4]
We want to make sure we're prepared for our kick-off in person meeting next week.

- Will we have access to the internet?
- Will there be a projector/display?
-- Should we send presentations ahead of time or present from our computers?
- Are there sticky notes, flipboards, or markers? (These supplies can be gotten at the 18F office if not).

**Comment by davemcorwin** [comment]
1. There will be wifi connectivity so you can access the internet if needed
2. There is a large monitor in the room if you need to connect to display your presentation
3. The room does not have a whiteboard but CRT could bring one in for the day if it is necessary
4. CRT will provide two flip charts and sticky notes
