### ISSUE TITLE
synthesize data from component leadership, JMD leadership, and JMD SDS meetings

### ISSUE THREAD

**Issue by timothy-spencer** [18F/doj-it-pa#46]
https://docs.google.com/document/d/1riKuyRKjTfYzi9CLK7PgF1qq1Zh_bjVV7oXoGwAUYXA/edit#heading=h.bgfo1lpafgi3

**Comment by Jacklynn** [comment]
@timothy-spencer Did you mean to include the JMD SDS folks in this? We had a different kind of conversation with them. I went over the notes and can add some notes in your doc!

**Comment by timothy-spencer** [comment]
@Jacklynn No, we didn't get the same sort of data from them, so their data wouldn't really work with the analysis that I was doing.

**Comment by Jacklynn** [comment]
Sounds good, I created a separate Mural for that interview, that I showed in this mornings meeting
