### ISSUE TITLE
Evaluate and answer in-progress `Arising Questions` (week 5)

### ISSUE THREAD

**Issue by davemcorwin** [18F/doj-it-pa#50]
- [x] Dave
- [x] Tim
- [x] Aviva
- [x] Nikki
- [x] Jacklynn

**Comment by Jacklynn** [comment]
[Arising Questions doc](https://docs.google.com/document/d/19_T2LMeIBqfUg-0clIzPGTUzFWSLM5Y4BIzocOAC9Xg/edit#heading=h.agptlc3nhd68)

I took my first pass at the questions, although there were some specific questions about services that we might have answered in the interviews that overlap with Tim's exercise & synthesis so I left them there to be better answered. I indicated my responses with "JP"

**Comment by nikzei** [comment]
The questions that I felt we didn't need to investigate anymore, I moved to "answered" and commented them.
