### ISSUE TITLE
Schedule follow up interviews to talk about specific service opportunities

### ISSUE THREAD

**Issue by Jacklynn** [18F/doj-it-pa#62]
related to #60

This may or may not be the same component folks we talked to before, depending on the services they brought up.

**Comment by Jacklynn** [comment]
Took a first pass at the scheduling email within Tim's doc, [here](https://docs.google.com/document/d/1cUsPR8ttlTno3FcwLH0d0UW0ZRRNsRT967J2MZp8NBQ/edit#bookmark=id.bzr2ino28w0n). The content can change however, I just wanted to make sure the services were paired up with the right component

**Comment by timothy-spencer** [comment]
Emails have been sent to components.

**Comment by timothy-spencer** [comment]
Have 1.5 out of the 3 scheduled.
