### ISSUE TITLE
Incorporate feedback into midway report

### ISSUE THREAD

**Issue by nikzei** [18F/doj-it-pa#82]
During our midway report feedback session, components/JMD identified a few areas that they wanted us to change/correct/update. Let's take care of these items so that they are reflected in the midway report that we include in the appendix of our final submission.

**Comment by davemcorwin** [comment]
https://docs.google.com/document/d/1M1Rc4IFCj_FcXXNjPN_6TKvpUATaIpZBbHKWeRC8ZRs/edit#
