### ISSUE TITLE
Add descriptions to the attachments

### ISSUE THREAD

**Issue by davemcorwin** [18F/doj-it-pa#86]

**Comment by Jacklynn** [comment]
This wasn't actually done, but I did it this morning: Appendix numbers in draft 2 updated, Appendix list in draft 2 updated, appendix compilation doc updated, appendix attachments updated and in [this drive folder](https://drive.google.com/drive/u/0/folders/1tEu3VNl7ly_alIrE3vShMTXEhJZpsi3y)
