### ISSUE TITLE
Incorporate more discussion of the process

### ISSUE THREAD

**Issue by davemcorwin** [18F/doj-it-pa#87]
Similarly to how we provided this information in the mid-project report

**Comment by Jacklynn** [comment]
Working on draft [here](https://docs.google.com/document/d/1dX7DSa1XWhQPUz5j7yT9JGKFUQ1zuR5MfRUvPuUwob0/edit#) if folks want follow along (contributions welcome!)

**Comment by davemcorwin** [comment]
> The Mid-point report states that the final report will be in similar format but it was vastly different—so summarizing the whole process in the final report would be helpful since this report is going to high level management who don’t have time to go through all the attachments.

- Allyson

**Comment by Jacklynn** [comment]
We ended up incorporating the structure of the midway into the final report with the additions of the new activity.
