### ISSUE TITLE
Add more key takeaways of consolidation opportunities in the report

### ISSUE THREAD

**Issue by davemcorwin** [18F/doj-it-pa#89]

**Comment by timothy-spencer** [comment]
Added a first draft where I pasted in the "good" candidates list from the consolidation candidate finding results doc.

**Comment by davemcorwin** [comment]
> Once again, please include a synopsis of the  good/bad candidates in the actual final report document—high level management do not have the time to dig through all the attachments.

-- Allyson

**Comment by timothy-spencer** [comment]
OK.  Added a section 6:  Components identified areas where consolidation was not likely to be successful.

**Comment by timothy-spencer** [comment]
Waiting for some approval to be rubbed on my changes in section 5/6.

**Comment by timothy-spencer** [comment]
redid this a couple of times.  Done.
